### ISSUE TITLE
When I call "openGTViewAddFinishHandler", I got error 405.

### ISSUE THREAD

**Issue by RacingWang** [GeeTeam/gtapp-ios-oc#1]
Hi. Is geetest available in Taiwan?
I try to run the iOS-sdk-failback-demo project. When I call "openGTViewAddFinishHandler", I got error 405 in web page.

**Comment by NikoXu** [comment]
Geetest is available in Taiwan.
Maybe that's our tech problem. We forbidden some untrusted ip yesterday. But now, we remove the limit.
Please try again.

**Comment by NikoXu** [comment]
Hmmm!
I think that because our failback system is not support cdn in this demo. In general, the failback system should be built up by sdk-user. So you should build up yours faiback strategy. 
If you should do it by yourslf, you should build server-sdk on your host server. You can check server-doc at http://www.geetest.com/install/sections/idx-server-sdk.html. 
And the faikback is a scheme for bad networking environment. You can get more information at https://github.com/GeeTeam/gtapp-ios-oc/blob/master/gt-iOS-sdk-failback%20-demo/geetest_ios_dev.rst#id15

**Comment by RacingWang** [comment]
Thank for reply. I will try to build server SDK later.
BTW, does geetest has localization in different language?

**Comment by NikoXu** [comment]
Sorry about that. We didn't. We'll add localization later.

**Comment by NikoXu** [comment]
Actually, localization support has been written in the web-front. But there isn't the api to open it . I'll add an api method in our iOS-SDK later.
